
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  host: <%= ENV['GL_DB_HOST'] %>
  port: <%= ENV['GL_DB_PORT'] %>
  database: grocery_link_development

test: &test
  <<: *default
  host: <%= ENV['GL_DB_HOST'] %>
  port: <%= ENV['GL_DB_PORT'] %>
  database: grocery_link_test

production:
  <<: *default
  database: grocery_link_production
  username: grocery_link
  password: <%= ENV['GROCERY_LINK_DATABASE_PASSWORD'] %>
